const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
const PRODUCT_DETAILS_REQ = 'PRODUCT_DETAILS_REQ';
const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
const CART_ADD_ITEM = 'CART_ADD_ITEM';
const REMOVE_CART  = 'REMOVE_CART ';
const  USER_SIGN_IN_SUCCESS = ' USER_SIGN_IN_SUCCESS';
const  USER_SIGN_IN_REQ = ' USER_SIGN_IN_REQ';
const  USER_SIGN_IN_FAIL = ' USER_SIGNFAILCESS';

 
export {PRODUCT_LIST_FAIL,
        PRODUCT_LIST_REQUEST,
        PRODUCT_LIST_SUCCESS, 
        PRODUCT_DETAILS_REQ,
        PRODUCT_DETAILS_FAIL,
        PRODUCT_DETAILS_SUCCESS ,
        CART_ADD_ITEM,
        REMOVE_CART ,
        USER_SIGN_IN_SUCCESS,
        USER_SIGN_IN_REQ,
        USER_SIGN_IN_FAIL
    };